apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-demo
  labels:
    app: devsecops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-demo
  template:
    metadata:
      labels:
        app: devsecops-demo
    spec:
      containers:
        - name: devsecops-demo
          image: ghcr.io/rupesh-hub/devsecops-demo-2025-11-18:sha-892154a84cc2a3eb4906e3c3d07cd9f0b9d609a5
          imagePullPolicy: Always
          ports:
            - containerPort: 8181
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 8181
#            initialDelaySeconds: 30
#            periodSeconds: 10
#          readinessProbe:
#            httpGet:
#              path: /
#              port: 8181
#            initialDelaySeconds: 5
#            periodSeconds: 5

      imagePullSecrets:
        - name: github-container-registry