apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops
  labels:
    app: devsecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      containers:
        - name: devsecops
          image: ghcr.io/rupesh-hub/devsecops-demo-2025-11-18:sha-b76caf31139d5c9ae3e72f84a419084ec30eaf55
          imagePullPolicy: Always
          ports:
            - containerPort: 8181
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 8181
#            initialDelaySeconds: 30
#            periodSeconds: 10
#          readinessProbe:
#            httpGet:
#              path: /
#              port: 8181
#            initialDelaySeconds: 5
#            periodSeconds: 5

      imagePullSecrets:
        - name: github-container-registry